name: Main

on:
  workflow_dispatch:
  push:
    branches: ['*']

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  checking-format:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
            node-version: 18

      - name: Setup pnpm
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
        uses: pnpm/action-setup@v2.2.4
        with:
            # Version of pnpm to install
            version: 7.21.0

      - name: GitHub Action for npx
        # You may pin to the exact commit or the version.
        # uses: mikeal/npx@e7aaefed7c9f2e83d493ff810f17fa5ccd7ed437
        uses: mikeal/npx@1.0.0

      - name: Install dependencies
        run: pnpm install

      - name: Check the formating
        run: npx -y prettier --check "src/**/*.ts"
  formating-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
            node-version: 18

      - name: Setup pnpm
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
        uses: pnpm/action-setup@v2.2.4
        with:
            # Version of pnpm to install
            version: 7.21.0

      - name: GitHub Action for npx
        # You may pin to the exact commit or the version.
        # uses: mikeal/npx@e7aaefed7c9f2e83d493ff810f17fa5ccd7ed437
        uses: mikeal/npx@1.0.0

      - name: Install dependencies
        run: pnpm install

      - name: Format the files
        run: npx -y prettier --write ./src/**/*.ts

      - run: git config --global user.email "actions@github.com"
      - run: git config --global user.name "GitHub Action"
      - run: git remote set-url origin https://lapstimeoff:${{ secrets.GITHUB_TOKEN }}@github.com/lapstimeoff/f1mv_watchgroups.git
      - run: git add .
      - run: git commit -m "Prettier edits"
      - run: git push origin HEAD:stable
    needs: checking-format
    if: ${{ failure() }}
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Use only 'java' to analyze code written in Java, Kotlin or both
        # Use only 'javascript' to analyze code written in JavaScript, TypeScript or both
        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript
        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.

        # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
        # queries: security-extended,security-and-quality


    # Autobuild attempts to build any compiled languages  (C/C++, C#, Go, or Java).
    # If this step fails, then you should remove it and run the build manually (see below)
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    # ℹ️ Command-line programs to run using the OS shell.
    # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun

    #   If the Autobuild fails above, remove it and uncomment the following three lines.
    #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.

    # - run: |
    #   echo "Run, Build Application using script"
    #   ./location_of_script_within_repo/buildscript.sh

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18
      
      - name: Setup pnpm
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
        uses: pnpm/action-setup@v2.2.4
        with:
          # Version of pnpm to install
          version: 7.21.0
        
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

  make-linux:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[NO-BUILD]')"
    needs: build

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18
      
      - name: Setup pnpm
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
        uses: pnpm/action-setup@v2.2.4
        with:
          # Version of pnpm to install
          version: 7.21.0
        
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build/release Electron app linux/x64
        run: pnpm make --arch=x64 --platform=linux

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: build
          path: |
            out/make/*
  make-windows:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[NO-BUILD]')"
    needs: build

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18
      
      - name: Setup pnpm
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
        uses: pnpm/action-setup@v2.2.4
        with:
          # Version of pnpm to install
          version: 7.21.0
        
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build/release Electron app win32/x64
        run: pnpm make --arch=x64 --platform=win32

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: build
          path: |
            out/make/*
  make-macos:
    runs-on: macos-12
    if: "!contains(github.event.head_commit.message, '[NO-BUILD]')"
    needs: build

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18
      
      - name: Setup pnpm
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
        uses: pnpm/action-setup@v2.2.4
        with:
          # Version of pnpm to install
          version: 7.21.0
        
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build/release Electron app darwin/universal
        run: pnpm make --arch=universal --platform=darwin

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: build
          path: |
            out/make/*
  delete-artifacts:
    runs-on: ubuntu-latest
    needs: ['make-windows', 'make-linux', 'make-macos']
    if: "!contains(github.event.head_commit.message, '!')"

    steps:
      - uses: geekyeggo/delete-artifact@v2
        with:
            name: build